import type { TemplateRegistryDefinition } from "../registry-types";

export const quickDeployLaunchpadDef: TemplateRegistryDefinition = {
  templateId: "quick_deploy_launchpad",
  version: "1.0.0",
  status: "active",
  rendererKey: "quick_deploy_launchpad",
  sourcePath: "src/devops-console/templates/quick-deploy-launchpad.tsx",
  title: "Quick Deploy Launchpad",
  description: "서비스 배포를 위한 런치패드 surface. 서비스명, 환경, 버전, preflight check 등을 표시하고 배포 시작/초안 새로고침 액션을 제공한다.",
  inputContract: {
    schemaVersion: "1.0",
    fields: [
      { path: "templateId", type: "string", required: true, description: "Template identifier", example: "quick_deploy_launchpad", enumValues: ["quick_deploy_launchpad"] },
      { path: "state", type: "string", required: true, description: "배포 상태", example: "ready", enumValues: ["ready", "deploying", "done"] },
      { path: "service", type: "string", required: true, description: "배포 대상 서비스명", example: "payments-api" },
      { path: "environment", type: "string", required: true, description: "배포 환경", example: "production" },
      { path: "recommendedVersion", type: "string", required: true, description: "추천 버전", example: "v1.2.3" },
      { path: "targetVersion", type: "string", required: true, description: "배포 대상 버전", example: "v1.2.3" },
      { path: "strategy", type: "string", required: false, description: "배포 전략", example: "rolling" },
      { path: "impactSummary", type: "string", required: false, description: "영향도 요약", example: "payments-api production 환경에 v1.2.3 배포" },
      { path: "preflightChecks", type: "string[]", required: false, description: "사전 검증 항목", example: ["3개 환경 확인됨"] },
      { path: "helperText", type: "string", required: false, description: "상태 안내 텍스트", example: "배포 준비 완료" },
    ],
  },
  selectionPolicyDoc: {
    intentKeys: ["deploy.start"],
    requiredFacts: ["deploy.serviceName", "deploy.selectedServiceContext"],
    optionalFacts: ["deploy.environment", "deploy.targetVersion"],
    reasonTemplate: "deploy.start intent에서 serviceName과 serviceContext가 준비되면 선택",
  },
  previewCases: [
    {
      id: "ready",
      title: "배포 준비 완료",
      payload: {
        templateId: "quick_deploy_launchpad",
        state: "ready",
        service: "payments-api",
        environment: "production",
        recommendedVersion: "v1.2.3",
        targetVersion: "v1.2.3",
        strategy: "rolling",
        impactSummary: "payments-api production 환경에 v1.2.3 배포",
        preflightChecks: ["3개 환경 확인됨", "5개 이미지 사용 가능"],
        helperText: "배포 준비 완료",
        primaryActionLabel: "배포 시작",
        secondaryActionLabel: "초안 새로 고침",
      },
    },
    {
      id: "deploying",
      title: "배포 진행 중",
      payload: {
        templateId: "quick_deploy_launchpad",
        state: "deploying",
        service: "payments-api",
        environment: "production",
        recommendedVersion: "v1.2.3",
        targetVersion: "v1.2.3",
        strategy: "rolling",
        impactSummary: "payments-api production 환경에 v1.2.3 배포 중",
        preflightChecks: ["환경 확인됨"],
        helperText: "배포 진행 중",
        primaryActionLabel: "완료 반영",
        secondaryActionLabel: "초안 새로 고침",
      },
    },
  ],
};
