import type { A2UIPartDefinition } from "./part-definition-types";

const DEPLOY_ROLLOUT_STEPS = ["이미지 Pull", "컨테이너 생성", "헬스체크 실행", "트래픽 전환", "최종 검증"];

export const DEPLOY_PREVIEW_PAYLOAD = {
  templateId: "deploy_launchpad",
  state: "ready",
  service: "payments-api",
  environment: "production",
  recommendedVersion: "v2.3.18-rc1",
  targetVersion: "v2.3.18-rc1",
  strategy: "rolling",
  impactSummary: "payments-api production 환경에 v2.3.18-rc1 배포",
  preflightChecks: [
    { label: "production 환경 확인", status: "pass" },
    { label: "ECR 이미지 push 검증", status: "pass" },
    { label: "최근 실패 배포 없음", status: "pass" },
  ],
  imageDetail: {
    repository: "payments-api",
    imageTag: "v2.3.18-rc1",
    imageUri: "123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/payments-api:v2.3.18-rc1",
    gitRef: "refs/heads/release/payments-2.3",
    commitSha: "a18fe902",
    imageDigest: "sha256:9e6dd0c3c7ad91e5fe7a1187a1f3c4be",
    buildStatus: "push_verified",
    pushedAt: "2026-03-25 12:10 KST",
  },
  requestDetail: {
    selectedImageId: "img-payments-2318",
    selectedImageUri: "123456789012.dkr.ecr.ap-northeast-2.amazonaws.com/payments-api:v2.3.18-rc1",
    service: "payments-api",
    environment: "production",
    cpu: "1024",
    memory: "2048",
    containerPort: "8080",
    desiredCount: "4",
    minimumHealthyPercent: "100",
    maximumPercent: "200",
    deploymentStrategy: "rolling",
    healthCheckPath: "/healthz/ready",
    healthCheckGracePeriod: "60",
    rollbackBaseline: "v2.3.17",
    requestedBy: "AI Assistant",
    executionProfile: "standard",
    operatorNote: "",
  },
  deploymentHistory: [
    {
      version: "v2.3.17",
      status: "succeeded",
      deployedBy: "release-bot",
      deployedAt: "2026-03-24 17:32 KST",
    },
    {
      version: "v2.3.16",
      status: "succeeded",
      deployedBy: "release-bot",
      deployedAt: "2026-03-22 09:18 KST",
    },
  ],
};

export const DEPLOY_PART_DEFINITIONS: A2UIPartDefinition[] = [
  {
    type: "DeployTargetSummaryBlock",
    label: "Deploy target",
    category: "deploy",
    description: "배포 대상 서비스, 환경, 버전, 전략을 수정 가능한 입력으로 보여줍니다.",
    defaultIdPrefix: "deploy-target",
    defaultProps: {
      service: { type: "binding", path: "payload.service" },
      environment: { type: "binding", path: "payload.environment" },
      targetVersion: { type: "binding", path: "payload.targetVersion" },
      recommendedVersion: { type: "binding", path: "payload.recommendedVersion" },
      strategy: { type: "binding", path: "payload.strategy" },
      impactSummary: { type: "binding", path: "payload.impactSummary" },
    },
    editorFields: [
      { kind: "bindingPath", prop: "service", label: "Service binding", defaultPath: "payload.service", required: true },
      { kind: "bindingPath", prop: "environment", label: "Environment binding", defaultPath: "payload.environment", required: true },
      { kind: "bindingPath", prop: "targetVersion", label: "Target version binding", defaultPath: "payload.targetVersion", required: true },
      { kind: "bindingPath", prop: "recommendedVersion", label: "Recommended version binding", defaultPath: "payload.recommendedVersion" },
      { kind: "bindingPath", prop: "strategy", label: "Strategy binding", defaultPath: "payload.strategy", required: true },
      { kind: "bindingPath", prop: "impactSummary", label: "Impact summary binding", defaultPath: "payload.impactSummary" },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
    requiredPayloadPaths: ["payload.service", "payload.environment", "payload.targetVersion", "payload.strategy"],
  },
  {
    type: "DeployArtifactBlock",
    label: "Deploy artifact",
    category: "deploy",
    description: "선택된 이미지/ECR artifact 상세를 image 등록 폼과 같은 입력으로 보여줍니다.",
    defaultIdPrefix: "deploy-artifact",
    defaultProps: {
      image: { type: "binding", path: "payload.imageDetail" },
      visibleFields: {
        type: "static",
        value: ["repository", "imageTag", "imageUri", "gitRef", "commitSha", "imageDigest", "buildStatus", "pushedAt"],
      },
    },
    editorFields: [
      { kind: "bindingPath", prop: "image", label: "Image detail binding", defaultPath: "payload.imageDetail", required: true },
      {
        kind: "staticStringList",
        prop: "visibleFields",
        label: "Visible fields",
        defaultValue: ["repository", "imageTag", "imageUri", "gitRef", "commitSha", "imageDigest", "buildStatus", "pushedAt"],
      },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
    requiredPayloadPaths: ["payload.imageDetail"],
  },
  {
    type: "DeployRequestConfigBlock",
    label: "Deploy request",
    category: "deploy",
    description: "ECS 스타일 배포 요청 설정을 request 생성 폼과 같은 입력으로 보여줍니다.",
    defaultIdPrefix: "deploy-request",
    defaultProps: {
      request: { type: "binding", path: "payload.requestDetail" },
      visibleFields: {
        type: "static",
        value: [
          "selectedImageId",
          "selectedImageUri",
          "service",
          "environment",
          "deploymentStrategy",
          "cpu",
          "memory",
          "containerPort",
          "desiredCount",
          "minimumHealthyPercent",
          "maximumPercent",
          "healthCheckPath",
          "healthCheckGracePeriod",
          "rollbackBaseline",
          "requestedBy",
          "executionProfile",
          "operatorNote",
        ],
      },
    },
    editorFields: [
      { kind: "bindingPath", prop: "request", label: "Request detail binding", defaultPath: "payload.requestDetail", required: true },
      {
        kind: "staticStringList",
        prop: "visibleFields",
        label: "Visible fields",
        defaultValue: [
          "selectedImageId",
          "selectedImageUri",
          "service",
          "environment",
          "deploymentStrategy",
          "cpu",
          "memory",
          "containerPort",
          "desiredCount",
          "minimumHealthyPercent",
          "maximumPercent",
          "healthCheckPath",
          "healthCheckGracePeriod",
          "rollbackBaseline",
          "requestedBy",
          "executionProfile",
          "operatorNote",
        ],
      },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
    requiredPayloadPaths: ["payload.requestDetail"],
  },
  {
    type: "DeployPreflightChecklistBlock",
    label: "Preflight checks",
    category: "deploy",
    description: "배포 전 검증 항목과 상태를 보여줍니다.",
    defaultIdPrefix: "deploy-preflight",
    defaultProps: {
      checks: { type: "binding", path: "payload.preflightChecks", fallback: [] },
    },
    editorFields: [
      { kind: "bindingPath", prop: "checks", label: "Checks binding", defaultPath: "payload.preflightChecks", fallback: [] },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
  },
  {
    type: "DeployRolloutProgressBlock",
    label: "Rollout progress",
    category: "deploy",
    description: "배포 시작 이후 rollout 단계를 상태에 맞춰 보여줍니다.",
    defaultIdPrefix: "deploy-rollout",
    defaultProps: {
      state: { type: "binding", path: "payload.state" },
      steps: { type: "static", value: DEPLOY_ROLLOUT_STEPS },
    },
    editorFields: [
      { kind: "bindingPath", prop: "state", label: "State binding", defaultPath: "payload.state", required: true },
      { kind: "staticStringList", prop: "steps", label: "Static steps", defaultValue: DEPLOY_ROLLOUT_STEPS },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
    requiredPayloadPaths: ["payload.state"],
  },
  {
    type: "DeploymentHistoryBlock",
    label: "Deployment history",
    category: "deploy",
    description: "최근 배포 이력을 보여줍니다.",
    defaultIdPrefix: "deploy-history",
    defaultProps: {
      rows: { type: "binding", path: "payload.deploymentHistory", fallback: [] },
    },
    editorFields: [
      { kind: "bindingPath", prop: "rows", label: "History rows binding", defaultPath: "payload.deploymentHistory", fallback: [] },
    ],
    previewPayload: DEPLOY_PREVIEW_PAYLOAD,
  },
];
